apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: false
    isDefault: true

  - name: Pyroscope
    type: phlare
    access: proxy
    url: http://pyroscope:4040
    version: 1
    editable: false
    jsonData:
        minStep: '15s'
        backendType: 'pyroscope'